refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)} - {l}: {m}{n})}"
  requests:
    kind: file
    path: "log/app.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: debug
  appenders:
    - stdout
    - requests
loggers:
  app::backend::db:
    level: debug
  app::requests:
    level: debug
    appenders:
      - requests
    additive: false